/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#a5f624",
        "on-error": "#ffffff",
        "on-surface-variant": "#45474c",
        "on-primary-fixed": "#161c27",
        "surface-dim": "#d7dadc",
        "on-primary-fixed-variant": "#414754",
        error: "#ba1a1a",
        "tertiary-container": "#162030",
        "inverse-primary": "#c1c6d7",
        "primary-container": "#1a202c",
        "on-tertiary-container": "#7d889b",
        "primary-fixed-dim": "#c1c6d7",
        tertiary: "#010817",
        "on-primary": "#ffffff",
        "inverse-surface": "#2d3133",
        "surface-container-low": "#f1f4f6",
        "surface-variant": "#e0e3e5",
        "inverse-on-surface": "#eef1f3",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-fixed": "#112000",
        "on-background": "#181c1e",
        "surface-container-lowest": "#ffffff",
        primary: "#030813",
        secondary: "#426900",
        surface: "#f7fafc",
        background: "#f7fafc",
        "surface-container": "#ebeef0",
        "secondary-fixed-dim": "#8fdb00",
        "on-tertiary-fixed-variant": "#3d4759",
        "primary-fixed": "#dde2f3",
        "surface-container-high": "#e5e9eb",
        "surface-tint": "#585e6c",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#314f00",
        "tertiary-fixed": "#d9e3f9",
        "on-tertiary-fixed": "#121c2c",
        "error-container": "#ffdad6",
        "on-surface": "#181c1e",
        "tertiary-fixed-dim": "#bdc7dc",
        "surface-bright": "#f7fafc",
        "on-secondary-container": "#456e00",
        "on-primary-container": "#828796",
        outline: "#76777c",
        "secondary-fixed": "#a8f928",
        "outline-variant": "#c6c6cc",
        "on-secondary": "#ffffff",
        brand: {
          50: "#f0f9ff",
          100: "#e0f2fe",
          500: "#0ea5e9",
          600: "#0284c7",
          700: "#0369a1",
          900: "#0c4a6e",
        },
      },
      fontFamily: {
        headline: ["'Plus Jakarta Sans'", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Lexend", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(-100%)" },
        },
      },
      animation: {
        marquee: "marquee 20s linear infinite",
      },
    },
  },
  plugins: [],
};
