const { PrismaClient } = require("@prisma/client");
const bcrypt = require("bcryptjs");
const prisma = new PrismaClient();

const REFEREES_30 = [
  // Top 10 Spotlight Elite Referees
  {
    email: "istvan.kovacs@leaguehub.local",
    name: "István Kovács",
    refereeBadge: "RIFA Elite",
    experienceYears: 17,
    phone: "+40 722 101 001",
    bio: "Arbitru RIFA Elite, delegat la finale europene UEFA Champions League și turnee finale mondiale.",
    image: "/images/referees/referee-2.jpg",
    coverPhotoUrl: "/images/referees/referee-2.jpg",
  },
  {
    email: "ovidiu.hategan@leaguehub.local",
    name: "Ovidiu Hațegan",
    refereeBadge: "RIFA Elite",
    experienceYears: 19,
    phone: "+40 722 101 002",
    bio: "Medic și arbitru internațional   Elite de peste 15 ani în UEFA Champions League și VAR Elite.",
    image: "/images/referees/referee-1.jpg",
    coverPhotoUrl: "/images/referees/referee-1.jpg",
  },
  {
    email: "radu.petrescu@leaguehub.local",
    name: "Radu Petrescu",
    refereeBadge: "RIFA First",
    experienceYears: 15,
    phone: "+40 722 101 003",
    bio: "Arbitru internațional   cu zeci de derby-uri naționale conduse impecabil și licență UEFA.",
    image: "/images/referees/referee-5.jpg",
    coverPhotoUrl: "/images/referees/referee-5.jpg",
  },
  {
    email: "horatiu.fesnic@leaguehub.local",
    name: "Horațiu Feșnic",
    refereeBadge: "RIFA First",
    experienceYears: 13,
    phone: "+40 722 101 004",
    bio: "Arbitru   categorie First, stil atletic și decizii ferme în teren la meciuri cu miză mare.",
    image: "/images/referees/referee-4.jpg",
    coverPhotoUrl: "/images/referees/referee-4.jpg",
  },
  {
    email: "marian.barbu@leaguehub.local",
    name: "Marian Barbu",
    refereeBadge: "RIFA Cat 2",
    experienceYears: 11,
    phone: "+40 722 101 005",
    bio: "Arbitru   tânăr și dinamic, cu prezențe regulate în cupele europene și campionatul național.",
    image: "/images/referees/referee-6.jpg",
    coverPhotoUrl: "/images/referees/referee-6.jpg",
  },
  {
    email: "andrei.chivulete@leaguehub.local",
    name: "Andrei Chivulete",
    refereeBadge: "RIFA Cat 2",
    experienceYears: 12,
    phone: "+40 722 101 006",
    bio: "Arbitru central  , specializat pe meciuri de mare intensitate și gestionarea conflictelor.",
    image: "/images/referees/referee-2.jpg",
    coverPhotoUrl: "/images/referees/referee-2.jpg",
  },
  {
    email: "sebastian.coltescu@leaguehub.local",
    name: "Sebastian Colțescu",
    refereeBadge: "Liga 1 Senior",
    experienceYears: 21,
    phone: "+40 722 101 007",
    bio: "Veteran al corpului de arbitri, peste 350 de meciuri conduse în primul eșalon național.",
    image: "/images/referees/referee-1.jpg",
    coverPhotoUrl: "/images/referees/referee-1.jpg",
  },
  {
    email: "iuliana.demetrescu@leaguehub.local",
    name: "Iuliana Demetrescu",
    refereeBadge: "RIFA Elite",
    experienceYears: 14,
    phone: "+40 722 101 008",
    bio: "Arbitră RIFA Elite, delegată la Campionatul Mondial Feminin și UEFA Women's Champions League.",
    image: "/images/referees/referee-3.jpg",
    coverPhotoUrl: "/images/referees/referee-3.jpg",
  },
  {
    email: "alina.pesu@leaguehub.local",
    name: "Alina Peșu",
    refereeBadge: "RIFA First",
    experienceYears: 11,
    phone: "+40 722 101 009",
    bio: "Arbitră internațională   First, arbitrează frecvent meciuri masculine de ligă superioară.",
    image: "/images/referees/referee-3.jpg",
    coverPhotoUrl: "/images/referees/referee-3.jpg",
  },
  {
    email: "catalin.popa@leaguehub.local",
    name: "Cătălin Popa",
    refereeBadge: "RIFA VAR",
    experienceYears: 16,
    phone: "+40 722 101 010",
    bio: "Specialist   VAR și arbitru central de ligă de elită, expert în analiza reluărilor video.",
    image: "/images/referees/referee-5.jpg",
    coverPhotoUrl: "/images/referees/referee-5.jpg",
  },

  // Remaining Official Roster (Rank 11 - 30)
  {
    email: "marcel.birsan@leaguehub.local",
    name: "Marcel Bîrsan",
    refereeBadge: "Liga 1 Pro",
    experienceYears: 14,
    phone: "+40 722 101 011",
    bio: "Arbitru cu mare experiență în partidele de play-off și meciuri tensionate.",
    image: "/images/referees/referee-4.jpg",
    coverPhotoUrl: "/images/referees/referee-4.jpg",
  },
  {
    email: "sorin.costreie@leaguehub.local",
    name: "Sorin Costreie",
    refereeBadge: "Liga 1 Pro",
    experienceYears: 10,
    phone: "+40 722 101 012",
    bio: "Arbitru central apreciat pentru condiția fizică de excepție și plasamentul optim.",
    image: "/images/referees/referee-6.jpg",
    coverPhotoUrl: "/images/referees/referee-6.jpg",
  },
  {
    email: "rares.vidican@leaguehub.local",
    name: "Rareș Vidican",
    refereeBadge: "Liga 1 Pro",
    experienceYears: 8,
    phone: "+40 722 101 013",
    bio: "Unul dintre arbitrii tineri de mare perspectivă din corpul național.",
    image: "/images/referees/referee-2.jpg",
    coverPhotoUrl: "/images/referees/referee-2.jpg",
  },
  {
    email: "mircea.grigoriu@leaguehub.local",
    name: "Mircea Grigoriu",
    refereeBadge: "RIFA Asistent",
    experienceYears: 15,
    phone: "+40 722 101 014",
    bio: "Arbitru asistent   de clasă mondială, prezent la partide din grupele Champions League.",
    image: "/images/referees/referee-1.jpg",
    coverPhotoUrl: "/images/referees/referee-1.jpg",
  },
  {
    email: "sebastian.gheorghe@leaguehub.local",
    name: "Sebastian Gheorghe",
    refereeBadge: "RIFA Asistent",
    experienceYears: 16,
    phone: "+40 722 101 015",
    bio: "Asistent   de elită, colaborator de cursă lungă al brigăzilor internaționale.",
    image: "/images/referees/referee-5.jpg",
    coverPhotoUrl: "/images/referees/referee-5.jpg",
  },
  {
    email: "radu.ghinguleac@leaguehub.local",
    name: "Radu Ghinguleac",
    refereeBadge: "RIFA Asistent",
    experienceYears: 14,
    phone: "+40 722 101 016",
    bio: "Arbitru asistent   cu sute de meciuri de primă ligă și prezențe internaționale constante.",
    image: "/images/referees/referee-4.jpg",
    coverPhotoUrl: "/images/referees/referee-4.jpg",
  },
  {
    email: "vasile.marinescu@leaguehub.local",
    name: "Vasile Marinescu",
    refereeBadge: "RIFA Asistent",
    experienceYears: 18,
    phone: "+40 722 101 017",
    bio: "Expert în poziționare pe linia de fund și decizii milimetrice de ofsaid.",
    image: "/images/referees/referee-6.jpg",
    coverPhotoUrl: "/images/referees/referee-6.jpg",
  },
  {
    email: "horia.mladinovici@leaguehub.local",
    name: "Horia Mladinovici",
    refereeBadge: "Liga 1 Pro",
    experienceYears: 12,
    phone: "+40 722 101 018",
    bio: "Arbitru central recunoscut pentru calmul și dialogul deschis cu jucătorii și antrenorii.",
    image: "/images/referees/referee-2.jpg",
    coverPhotoUrl: "/images/referees/referee-2.jpg",
  },
  {
    email: "viorel.flueran@leaguehub.local",
    name: "Viorel Flueran",
    refereeBadge: "Liga 1 Pro",
    experienceYears: 10,
    phone: "+40 722 101 019",
    bio: "Arbitru central din Craiova, stil tehnic și imparțialitate recunoscută.",
    image: "/images/referees/referee-1.jpg",
    coverPhotoUrl: "/images/referees/referee-1.jpg",
  },
  {
    email: "szabolcs.kovacs@leaguehub.local",
    name: "Szabolcs Kovács",
    refereeBadge: "Liga 1 Pro",
    experienceYears: 9,
    phone: "+40 722 101 020",
    bio: "Arbitru central cu profil modern, excelent în aplicarea avantajului și a spiritului de joc.",
    image: "/images/referees/referee-5.jpg",
    coverPhotoUrl: "/images/referees/referee-5.jpg",
  },
  {
    email: "florin.andrei@leaguehub.local",
    name: "Florin Andrei",
    refereeBadge: "Liga 1 Central",
    experienceYears: 11,
    phone: "+40 722 101 021",
    bio: "Arbitru central de ligă de elită din Târgu Mureș.",
    image: "/images/referees/referee-4.jpg",
    coverPhotoUrl: "/images/referees/referee-4.jpg",
  },
  {
    email: "iulian.calin@leaguehub.local",
    name: "Iulian Călin",
    refereeBadge: "Liga 1 Central",
    experienceYears: 13,
    phone: "+40 722 101 022",
    bio: "Arbitru cu zeci de sezoane în primul eșalon național și meciuri internaționale amicale.",
    image: "/images/referees/referee-6.jpg",
    coverPhotoUrl: "/images/referees/referee-6.jpg",
  },
  {
    email: "lucian.rusandu@leaguehub.local",
    name: "Lucian Rusandu",
    refereeBadge: "Liga Pro Central",
    experienceYears: 14,
    phone: "+40 722 101 023",
    bio: "  cu vastă experiență în gestionarea partidelor decisive.",
    image: "/images/referees/referee-2.jpg",
    coverPhotoUrl: "/images/referees/referee-2.jpg",
  },
  {
    email: "bogdan.dumitrache@leaguehub.local",
    name: "Bogdan Dumitrache",
    refereeBadge: "Liga Pro Central",
    experienceYears: 8,
    phone: "+40 722 101 024",
    bio: "Arbitru tânăr și promovat recent în brigăzile de ligă superioară.",
    image: "/images/referees/referee-1.jpg",
    coverPhotoUrl: "/images/referees/referee-1.jpg",
  },
  {
    email: "mihai.amoraritei@leaguehub.local",
    name: "Mihai Amorăriței",
    refereeBadge: "Regional Banat",
    experienceYears: 7,
    phone: "+40 722 101 025",
    bio: "Arbitru coordonator pentru competițiile regionale din zona Banat și Timișoara.",
    image: "/images/referees/referee-5.jpg",
    coverPhotoUrl: "/images/referees/referee-5.jpg",
  },
  {
    email: "stefan.dumitrache@leaguehub.local",
    name: "Ștefan Dumitrache",
    refereeBadge: "Liga 1 Asistent",
    experienceYears: 9,
    phone: "+40 722 101 026",
    bio: "Asistent de linie cu procentaj de peste 98% în semnalizarea corectă a ofsaidurilor.",
    image: "/images/referees/referee-4.jpg",
    coverPhotoUrl: "/images/referees/referee-4.jpg",
  },
  {
    email: "alexandru.cerei@leaguehub.local",
    name: "Alexandru Cerei",
    refereeBadge: "Liga Pro Asistent",
    experienceYears: 10,
    phone: "+40 722 101 027",
    bio: "Arbitru asistent de prim rang din Cluj-Napoca, delegat la meciuri internaționale de tineret.",
    image: "/images/referees/referee-6.jpg",
    coverPhotoUrl: "/images/referees/referee-6.jpg",
  },
  {
    email: "bogdan.gheorghe@leaguehub.local",
    name: "Bogdan Gheorghe",
    refereeBadge: "Regional Tineret",
    experienceYears: 6,
    phone: "+40 722 101 028",
    bio: "Arbitru tânăr specializat pe campionatele de juniori de elită și turnee regionale.",
    image: "/images/referees/referee-2.jpg",
    coverPhotoUrl: "/images/referees/referee-2.jpg",
  },
  {
    email: "cristian.balaj@leaguehub.local",
    name: "Cristian Balaj",
    refereeBadge: "Supervizor Arbitri",
    experienceYears: 25,
    phone: "+40 722 101 029",
    bio: "Fost mare arbitru  , actual observator și instructor federal pentru corpul de arbitri.",
    image: "/images/referees/referee-1.jpg",
    coverPhotoUrl: "/images/referees/referee-1.jpg",
  },
  {
    email: "alexandru.deaconu@leaguehub.local",
    name: "Alexandru Deaconu",
    refereeBadge: "Expert Observator",
    experienceYears: 24,
    phone: "+40 722 101 030",
    bio: "Expert   și formator de arbitri internaționali, responsabil de calitatea arbitrajului.",
    image: "/images/referees/referee-5.jpg",
    coverPhotoUrl: "/images/referees/referee-5.jpg",
  },
];

async function main() {
  const hash = await bcrypt.hash("arbitru123", 10);

  for (const ref of REFEREES_30) {
    await prisma.user.upsert({
      where: { email: ref.email },
      update: {
        name: ref.name,
        role: "referee",
        refereeBadge: ref.refereeBadge,
        experienceYears: ref.experienceYears,
        phone: ref.phone,
        bio: ref.bio,
        image: ref.image,
        coverPhotoUrl: ref.coverPhotoUrl,
      },
      create: {
        email: ref.email,
        name: ref.name,
        passwordHash: hash,
        role: "referee",
        refereeBadge: ref.refereeBadge,
        experienceYears: ref.experienceYears,
        phone: ref.phone,
        bio: ref.bio,
        image: ref.image,
        coverPhotoUrl: ref.coverPhotoUrl,
      },
    });
  }

  console.log("Successfully seeded 30 official referees with genuine human portraits! ✓");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
